[package]
name = "aleo-wasm"
version = "0.2.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Aleo"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/aleo"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aleo-account = { path = "../rust/account" }

rand = { version = "0.8" }
getrandom = { version = "0.2.2", features = ["js"] }
wasm-bindgen = { version = "0.2.71" }

[dev-dependencies]
wasm-bindgen-test = { version = "0.3.20" }
