[package]
name = "aleo-wasm"
version = "0.2.0"
authors = ["The Aleo Team <hello@aleo.org>"]
description = "Aleo"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/aleo"
keywords = ["aleo", "cryptography", "blockchain", "decentralized", "zero-knowledge"]
categories = ["cryptography::cryptocurrencies", "operating-systems"]
include = ["Cargo.toml", "src", "README.md", "LICENSE.md"]
license = "GPL-3.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies.aleo-account]
path = "../rust/account"

[dependencies.aleo-environment]
path = "../rust/environment"

[dependencies.aleo-record]
path = "../rust/record"

[dependencies.snarkvm-dpc]
version = "0.5.5"
default-features = false
features = ["wasm"]

[dependencies.snarkvm-utilities]
version = "0.5.5"
default-features = false

[dependencies.getrandom]
version = "0.2.3"
features = ["js"]

[dependencies.hex]
version = "0.4.3"

[dependencies.rand]
version = "0.8"

[dependencies.wasm-bindgen]
version = "0.2.74"

[dev-dependencies.snarkvm-algorithms]
version = "0.5.5"
default-features = false
features = ["wasm"]

[dev-dependencies.wasm-bindgen-test]
version = "0.3.24"
